version: "3.9"

services:
  tiltify-donation-stats:
    container_name: tiltify-donation-stats
    image: codescot/tiltify-donation-stats
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: 
      - tiltify-donation-stats.env
