version: "3.9"

services:
  donation-analytics-core:
    container_name: donation-analytics-core
    image: codescot/donation-analytics-core
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: 
      - donation-analytics-core.env
