version: "3.9"

services:
  thenooktiltify:
    container_name: thenooktiltify
    image: codescot/thenooktiltify
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: 
      - thenooktiltify.env
